cookie:
  expiry_days: 30
  key: JIJLzWvUhh
  name: auth_main
credentials:
  usernames:
    gonfreecss:
      email: gonfreecss@gmail.com
      name: Gon Freecss
      password: $2b$12$NsNplsVfALopGpvqhB2L3ehT9pUE0JzfAiCP66G1GF4NAswaac3gi
    killuazoldyck:
      email: killuazoldyck@gmail.com
      name: Killua Zoldyck
      password: $2b$12$92Xwx4YVwcTMRaofOE1eD.o/m8Gfxhk2yNDpHIXKAYLa8sO5M98WK
preauthorized:
  emails:
  - ginfreecss@gmail.com
